# Generated by Django 3.2.13 on 2022-06-25 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Equipos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('abreviatura', models.CharField(max_length=8)),
                ('nombre_DT', models.CharField(max_length=20)),
                ('cant_jugadores', models.IntegerField(max_length=35)),
                ('escudo', models.ImageField(blank=True, null=True, upload_to='Equipos/escudos/')),
            ],
        ),
        migrations.CreateModel(
            name='Jugadores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('dorsal', models.IntegerField(max_length=99)),
                ('posicion', models.CharField(max_length=15)),
                ('equipo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.equipos')),
            ],
        ),
    ]
