# Generated by Django 3.2.13 on 2022-06-25 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Torneos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
                ('cant_equipos', models.IntegerField(max_length=30)),
                ('cant_jugadores_por_lado', models.IntegerField(max_length=10)),
                ('cant_partidos', models.IntegerField(max_length=2)),
            ],
        ),
    ]
