# Generated by Django 3.2.13 on 2022-06-25 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0002_torneos'),
    ]

    operations = [
        migrations.RenameField(
            model_name='torneos',
            old_name='cant_equipos',
            new_name='cantidad_equipos',
        ),
        migrations.RenameField(
            model_name='torneos',
            old_name='cant_jugadores_por_lado',
            new_name='cantidad_jugadores_por_lado',
        ),
        migrations.RemoveField(
            model_name='torneos',
            name='cant_partidos',
        ),
    ]
