# Generated by Django 3.2.13 on 2022-06-25 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0004_posicionesjugadores'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jugadores',
            name='posicion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Equipos.posicionesjugadores'),
        ),
        migrations.AlterField(
            model_name='posicionesjugadores',
            name='posicion',
            field=models.CharField(max_length=35),
        ),
    ]
