# Generated by Django 3.2.13 on 2022-07-01 22:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0009_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='Avatar/'),
        ),
    ]
