# Generated by Django 3.2.13 on 2022-07-12 22:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Equipos', '0011_profile'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
